### ISSUE TITLE
関数名修正案

### ISSUE THREAD

**Issue by hagitaku** [hokto/algorithms#1]
暇なのでissue投げます
無視しても全く問題ないです

ふわっと読み取った命名規則
* クラス名 : アッパーキャメルケース
* 関数名 : スネークケース
* 変数名 : スネークケース

関数名ルール
状態を判定する関数は`is_`から始まる

いくつか関数名(メソッド名)の修正案があります

## find関数
https://github.com/hokto/algorithms/blob/49e67907dd541f56fd6a8e53d50dc98b7dd00ac8/RedBlackTree/RedBlackTree.hpp#L367-L382
`find`関数ですが、関数名から何をfindするのか予測が困難なので`find_node_by_key`といった名前が好ましいです

## is_find関数
https://github.com/hokto/algorithms/blob/49e67907dd541f56fd6a8e53d50dc98b7dd00ac8/RedBlackTree/RedBlackTree.hpp#L385-L392
`is_find`関数も同様です

## empty関数
https://github.com/hokto/algorithms/blob/49e67907dd541f56fd6a8e53d50dc98b7dd00ac8/RedBlackTree/RedBlackTree.hpp#L394-L401
わかりやすくて良いです
この関数だけ`is_`がついていないのはc++の標準ライブラリを意識していますか?

## 規則揺れ
https://github.com/hokto/algorithms/blob/49e67907dd541f56fd6a8e53d50dc98b7dd00ac8/RedBlackTree/RedBlackTree.hpp#L339-L365
`preorder`と`postorder`は命名の表現が同一ですが`solve_order`だけなんか違います
そういう日もあると思います

**Comment by hagitaku** [comment]
昨日言ってたやつはこれ
https://github.com/hokto/algorithms/blob/49e67907dd541f56fd6a8e53d50dc98b7dd00ac8/RedBlackTree/RedBlackTree.hpp#L216

```cpp
delete subroot;
```
配列の場合は
```cpp
delete[] subroot;
```

**Comment by hokto** [comment]
ほんとだ, deleteの文法間違ってるね.
そこも含めて修正しておきます.

**Comment by hokto** [comment]
Issueでの指摘点を参考に以下の通りメソッド名及びメンバ変数名を変更しました.
### find → find_node_by_key
https://github.com/hokto/algorithms/blob/5f6d8f35c946c3578c4248ee2e999e2dbadbba6b/RedBlackTree/RedBlackTree.hpp#L373-L388
Issueで指摘いただいた命名が一番理解しやすいと感じたためそのまま使いました.

### is_find → is_find_node_by_key
https://github.com/hokto/algorithms/blob/5f6d8f35c946c3578c4248ee2e999e2dbadbba6b/RedBlackTree/RedBlackTree.hpp#L390-L398
こちらについても`find_node_by_key`と同様です.

### empty → is_empty
https://github.com/hokto/algorithms/blob/5f6d8f35c946c3578c4248ee2e999e2dbadbba6b/RedBlackTree/RedBlackTree.hpp#L400-L407
c++のSTLに準拠した書き方にしていましたが, is_*に統一した方がわかりやすいのでこちらも統一しました.

### ordersの命名について
https://github.com/hokto/algorithms/blob/5f6d8f35c946c3578c4248ee2e999e2dbadbba6b/RedBlackTree/RedBlackTree.hpp#L323-L371
指摘された通り規則がバラバラだったため, 始めを動作(init, get, solve)としアンダーバーで繋いだ後, `orders`もしくは各`order`の名称とするように統一しました.
これに合わせて, `order`系統のリストが初期化されているかを表すメンバ変数名を`is_init_orders`に変更しました.

### deleteの文法ミス
https://github.com/hokto/algorithms/blob/5f6d8f35c946c3578c4248ee2e999e2dbadbba6b/RedBlackTree/RedBlackTree.hpp#L233-L236
`delete`の書き方を間違っていたため, 正しい書き方に変更しました.
他の箇所についても同様に修正しています.

現時点でのIssueに対する修正は以上です.
確認よろしくお願いします.

**Comment by hagitaku** [comment]
修正確認しました
対応していただきありがとうございます!!
